version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "05:30"
    timezone: Australia/Brisbane
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.8.3
    - 16.9.1
  - dependency-name: nunit
    versions:
    - 3.13.0
    - 3.13.1
  - dependency-name: Newtonsoft.Json
    versions:
    - 12.0.3
